name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # Здесь мы принудительно переводим название в нижний регистр
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      - name: Build
        run: dotnet build **/*.csproj --no-restore --configuration Release

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Вот это исправит твою ошибку с заглавными буквами
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Используем команду lower, чтобы Docker не ругался
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/islabapp:latest
